export enum IconName {
  Analytics = "Analytics",
  ArrowUp = "ArrowUp",
  ArrowDown = "ArrowDown",
  Close = "Close",
  RequestManagement = "RequestManagement",
  RoutePlanning = "RoutePlanning",
  EDO = "EDO",
  Email = "Email",
  ListDots = "ListDots",
  CommentAvatarGreen = "CommentAvatarGreen",
  CommentAvatarBlue = "CommentAvatarBlue",
  Skype = "Skype",
  Phone = "Phone",
  Telegram = "Telegram",
  TenderDoc = "TenderDoc",
  Tracking = "Tracking",
  up = "up",
}
