import './globals.css'
import {Nunito_Sans} from 'next/font/google'

const NUNITO_SANS = Nunito_Sans({subsets: ['latin', "cyrillic-ext", "cyrillic"]})

export const metadata = {
  title: 'Intelogis',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={NUNITO_SANS.className}>{children}</body>
    </html>
  )
}
